version: '3'

services:
  auction-scraping:
    image: auction-scraping
    pull_policy: never
    restart: always
    container_name: auction-scraping
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs:/var/log
      - /opt/auto-deploy/vpn/brazil/credentials.ovpn:/etc/openvpn/credentials.ovpn
      - /opt/auto-deploy/vpn/brazil/auth.txt:/etc/openvpn/auth.txt
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    deploy:
      resources:
        limits:
          memory: 800M

networks:
  default:
    external:
      name: external-sol-apis
