version: '3'

services:
  auction-scraping:
    image: auction-scraping
    pull_policy: never
    restart: always
    container_name: auction-scraping
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/auto-deploy/logs/auction-scraping:/var/log
      - /opt/auto-deploy/vpn/brazil/credentials.ovpn:/etc/openvpn/credentials.ovpn
      - /opt/auto-deploy/vpn/brazil/auth.txt:/etc/openvpn/auth.txt
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      - external-sol-apis
      - logging-network
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "service=auction-scraping,type=service"
        loki-retries: "5"
        loki-batch-size: "400"
        mode: "non-blocking"
    deploy:
      resources:
        limits:
          memory: 800M

networks:
  logging-network:
    external: true
  external-sol-apis:
    external: true
